force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <displayFormat>User Id-{000}</displayFormat>
        <label>User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Redemption_Points__c.field-meta.xml
<CustomField>
    <fullName>Redemption_Points__c</fullName>
    <label>Redemption Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User__c/fields/User_Liginname__c.field-meta.xml
<CustomField>
    <fullName>User_Liginname__c</fullName>
    <label>User Loginname</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/User_Password__c.field-meta.xml
<CustomField>
    <fullName>User_Password__c</fullName>
    <label>User Password</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/User_Points_Last_Reimburse_Date__c.field-meta.xml
<CustomField>
    <fullName>User_Points_Last_Reimburse_Date__c</fullName>
    <label>User Points Last Reimburse Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User__c/fields/User_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>User_s_Last_Name__c</fullName>
    <label>User&apos;s Last Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/redeemptionApex.cls
public with sharing class redeemptionApex {
    
    @AuraEnabled(cacheable=true)
    public static User__c getUserInfo(String username, String password) {
        // Implement logic to retrieve user information based on the username and password.
        // You should validate the credentials and query the custom object.

        // Example query:
        User__c user = [SELECT Id, First_Name__c, Redemption_Points__c ,User_s_Last_Name__c,User_Points_Last_Reimburse_Date__c,User_Liginname__c
                        FROM User__c WHERE User_Liginname__c = :username AND User_Password__c = :password LIMIT 1];

        return user;
    }

    @AuraEnabled
    public static User__c redeemUserPoints(Id userId, Integer pointsToRedeem) {
        // Implement logic to redeem points for the user.
        // Update the Redeemable_Points__c field and perform any necessary validation.

        User__c user = [SELECT Id, First_Name__c,  Redemption_Points__c,User_Liginname__c 
                        FROM User__c WHERE Id = :userId LIMIT 1];
        user.Redemption_Points__c = user.Redemption_Points__c - pointsToRedeem;

        update user;

        return user;
    }
}