force-app/main/default/objects/Add__c/Add__c.object-meta.xml
<CustomObject>
    <label>Add</label>
    <nameField>
        <displayFormat>Ad-{000}</displayFormat>
        <label>Advertisement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_Add__c/Assign_Add__c.object-meta.xml
<CustomObject>
    <label>Assign Add</label>
    <nameField>
        <displayFormat>MAP-{000}</displayFormat>
        <label>Mapping Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assign Adds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_Add__c/fields/Add__c.field-meta.xml
<CustomField>
    <fullName>Add__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Add</label>
    <referenceTo>Add__c</referenceTo>
    <relationshipLabel>Assign Adds</relationshipLabel>
    <relationshipName>Assign_Adds</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assign_Add__c/fields/UniqueIdentifier__c.field-meta.xml
<CustomField>
    <fullName>UniqueIdentifier__c</fullName>
    <label>UniqueIdentifier</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assign_Add__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Assign Adds</relationshipLabel>
    <relationshipName>Assign_Adds</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <displayFormat>User Id-{000}</displayFormat>
        <label>User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NewFilterAssignAd.cls
public class NewFilterAssignAd {
    
    @AuraEnabled
    public static List<Id> newCreateAssignAd (List<User__c> selUser, List<Add__c> selAd){
        // Assuming you have two lists: userList and clientList

            List<Assign_Add__c> newAssignments = new List<Assign_Add__c>();
        
            for (User__c user : selUser) {
                for (Add__c add	 : selAd) {
                    // Create a unique identifier for the pairing
                    String uniqueIdentifier = user.Id + '-' + add.Id;
        
                    // Check if a record with the same pairing already exists
                    if (!assignmentExists(uniqueIdentifier)) {
                        Assign_Add__c assignment = new Assign_Add__c(
                            User__c = user.Id,  
                            Add__c = add.Id,  
                            UniqueIdentifier__c = uniqueIdentifier );
        
                    	newAssignments.add(assignment);
                	} 
                    else {
                    // Handle the error or log it
                    System.debug('Assignment already exists for User: ' + user.Name + ' and Add: ' + add.Name);
                    // You can also add these to a list to handle the error messages more formally
                	}
            	}
        	}
        
        	List<Id> createdRecordIds = new List<Id>();
            // Insert the new assignment records
            if (!newAssignments.isEmpty()) {
                
                
                insert newAssignments;
                
                for (Assign_Add__c record : newAssignments) {
                        createdRecordIds.add(record.Id);
            	}	
    		}
        return createdRecordIds;
	}

    // Method to check if a UserClientAssignment record with the given unique identifier already exists
    public static Boolean assignmentExists(String uniqueIdentifier) {
        List<Assign_Add__c> existingAssignments = [SELECT Id FROM Assign_Add__c WHERE UniqueIdentifier__c = :uniqueIdentifier LIMIT 1];

        return !existingAssignments.isEmpty();
    }
    
}