force-app/main/default/objects/Add__c/Add__c.object-meta.xml
<CustomObject>
    <label>Add</label>
    <nameField>
        <displayFormat>Ad-{000}</displayFormat>
        <label>Advertisement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_Add__c/Assign_Add__c.object-meta.xml
<CustomObject>
    <label>Assign Add</label>
    <nameField>
        <displayFormat>MAP-{000}</displayFormat>
        <label>Mapping Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assign Adds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_Add__c/fields/Add__c.field-meta.xml
<CustomField>
    <fullName>Add__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Add</label>
    <referenceTo>Add__c</referenceTo>
    <relationshipLabel>Assign Adds</relationshipLabel>
    <relationshipName>Assign_Adds</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assign_Add__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Assign Adds</relationshipLabel>
    <relationshipName>Assign_Adds</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <displayFormat>User Id-{000}</displayFormat>
        <label>User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssignAd.cls
public with sharing class AssignAd {
    
    @AuraEnabled
    public static List<Id> createAssignAd(List<User__c> selUser, List<Add__c> selAd){
       List<Assign_Add__c> asad = new List<Assign_Add__c>();

        Integer i = 0;
        Integer j = 0;
        Integer selAdSize = selAd.size();
        Integer selUserSize = seluser.size();
    

        for (i=0;i < selUserSize; i++){
            for (j=0; j < selAdSize ; j++) 
                {
                    Assign_Add__c Obj =  new Assign_Add__c();
                    Obj.User__c = selUser[i].Id;
                    Obj.Add__c = selAd[j].Id;
                    asad.add(obj);
                }
        }
        System.System.debug('asad:'+asad);

        List<Id> createdRecordIds = new List<Id>();
        
        try {
                // Insert the new record
                insert asad;

                // If successful, get the Id of the created record
                for (Assign_Add__c record : asad) {
                    createdRecordIds.add(record.Id);
                }
            }catch (DmlException e) {
                // Handle any exceptions or errors
                // You can log the error, display an error message, or take appropriate action.
                System.debug('Error creating records: ' + e.getMessage());
            }
    
            // Log the created record IDs
            System.debug('Created record Ids: ' + createdRecordIds);
    
            // Return the list of created record IDs to the Lightning Web Component
            return createdRecordIds;

        
  
    }
    
}