force-app/main/default/objects/Add__c/Add__c.object-meta.xml
<CustomObject>
    <label>Add</label>
    <nameField>
        <displayFormat>Ad-{000}</displayFormat>
        <label>Advertisement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Add__c/fields/Advertisement_Title__c.field-meta.xml
<CustomField>
    <fullName>Advertisement_Title__c</fullName>
    <label>Advertisement Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <displayFormat>User Id-{000}</displayFormat>
        <label>User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NewAssignAd.cls
public with sharing class NewAssignAd {
    
    @AuraEnabled
    public static List<User__c> getUserList(){
       
        List<User__c> userList = [SELECT Id,Name,First_Name__c from User__c ORDER BY Name ASC];
        return userList;
    }

    @AuraEnabled
    public static List<Add__c> getAdList(){
        
        List<Add__c> adList = [SELECT Id,Name,Advertisement_Title__c from Add__c ORDER BY Name ASC];
        return adList;
    }
}